#pragma once

#include "AWC/AWCusing.h"
#include "AWC/AWCException.h"
#include "AWC/AWCfwd.h"

#include "AWC/Operation/AntiOperation.h"
#include "AWC/Operation/Attack.h"
#include "AWC/Operation/Composed.h"
#include "AWC/Operation/Custom.h"
#include "AWC/Operation/Move.h"
#include "AWC/Operation/Operation.h"
#include "AWC/Operation/OperationI.h"
#include "AWC/Operation/StatMod.h"
#include "AWC/Operation/TakeDmg.h"
#include "AWC/Operation/UpdateFlag.h"

#include "AWC/Area/TileGraph.h"
#include "AWC/Area/TileNode.h"

#include "AWC/Area/Area.h"
#include "AWC/Area/AreaI.h"

#include "AWC/Area/AreaComp.h"
#include "AWC/Area/AreaConstraints.h"
#include "AWC/Area/AreaDesc.h"
#include "AWC/Area/AreaDescComp.h"
#include "AWC/Area/AreaDescDecorator.h"
#include "AWC/Area/AreaDescI.h"

#include "AWC/Unit/MovementDesc.h"
#include "AWC/Unit/MovementDescType.h"
#include "AWC/Unit/Unit.h"
#include "AWC/Unit/UnitAttack.h"
#include "AWC/Unit/UnitMovement.h"
#include "AWC/Unit/UnitType.h"
#include "AWC/Unit/Weapon.h"
#include "AWC/Unit/WeaponType.h"

#include "AWC/Command.h"
#include "AWC/CostTable.h"
#include "AWC/Directions.h"
#include "AWC/Entity.h"
#include "AWC/Event.h"
#include "AWC/Game.h"
#include "AWC/Map.h"
#include "AWC/Pathfinding.h"
#include "AWC/Player.h"
#include "AWC/Process.h"
#include "AWC/Range.h"
#include "AWC/Tile.h"
#include "AWC/TileType.h"
#include "AWC/Turn.h"