#pragma once

class Command;
class CostTable;
class CostTableI;
class FixedCostTable;
class Map;
class Tile;
class TileGraph;
class TileNode;
class TilePattern;
class TilePatternI;
class TilePatternUnion;
class TilePatternDiff;
class TilePatternIntersect;
class TilePatternConstraints;
class TilePatternDesc;
class TilePatternDescI;
class TPDFixedRange;
class TPDFixedCost;
class Unit;
class UnitAttack;
class UnitMovement;
class UnitMovementDesc;
class UnitType;
class UnitWeapon;